"use strict";
exports.__esModule = true;
var reportCard_1 = require("../ReportCard/reportCard");
var subject_1 = require("../Subject/subject");
var section_1 = require("../Section/section");
var student_1 = require("../Student/student");
var marks_1 = require("../Mark/marks");
var teacher_1 = require("../Teacher/teacher");
var math = new subject_1.Subject("Mathematics");
var science = new subject_1.Subject("Science");
var sansksrit = new subject_1.Subject("Sansksrit");
var computerScience = new subject_1.Subject("ComputerScience");
var markmath = new marks_1.Marks(math, 77);
var markscience = new marks_1.Marks(science, 88);
var makrsansksrit = new marks_1.Marks(sansksrit, 81);
var markcomputerScience = new marks_1.Marks(computerScience, 89);
var Saurabh = new student_1.Student("Saurabh Mishra", [1999, 1, 14]);
var report1 = new reportCard_1.ReportCard([markmath, markscience, markcomputerScience, makrsansksrit], Saurabh);
Saurabh.setReportCard(report1);
console.log(Saurabh.getReportCard());
var Shubham = new teacher_1.Teacher("Shubham Mishra", [1987, 9, 11]);
var Shivam = new teacher_1.Teacher("Shivam Singh", [1990, 11, 14]);
var tulip = new section_1.Section("Tulip");
var rose = new section_1.Section("Rose");
tulip.setTeacher(Shubham);
console.log(tulip.getTeacherByName("Shubham Mishra"));
